target = "all"
paths = "."
recursive = true
exclude = [
    "test_app",
]
manifest_file = [
    "bdc_motor/.build-test-rules.yml",
    "ccomp_timer/.build-test-rules.yml",
    "coremark/.build-test-rules.yml",
    "esp_encrypted_img/.build-test-rules.yml",
    "esp_serial_slave_link/.build-test-rules.yml",
    ".build-test-rules.yml",
]
check_warnings = true

# build related options
build_dir = "build_@t_@w"
parallel_count = 5
