target = "all"
paths = "."
recursive = true
exclude = [
    "test_app",
]
manifest_file = [
    "bdc_motor/.build-test-rules.yml",
    ".build-test-rules.yml",
]
check_warnings = true

# build related options
build_dir = "build_@t_@w"
parallel_count = 5
