name: Push components to Espressif Component Service

on:
  push:
    branches:
      - master

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Upload components to component service
        uses: espressif/upload-components-ci-action@v1
        with:
          directories: >
            bdc_motor;
            cbor;
            coap;
            eigen;
            esp_delta_ota;
            esp_encrypted_img;
            esp_jpeg;
            esp_serial_slave_link;
            expat;
            fmt;
            jsmn;
            json_generator;
            json_parser;
            led_strip;
            libpng;
            libsodium;
            nghttp;
            pcap;
            pid_ctrl;
            qrcode;
            quirc;
            sh2lib;
            usb/esp_modem_usb_dte;
            usb/esp_tinyusb;
            usb/usb_host_cdc_acm;
            usb/usb_host_ch34x_vcp;
            usb/usb_host_cp210x_vcp;
            usb/usb_host_ftdi_vcp;
            usb/usb_host_msc;
            usb/usb_host_uvc;
            usb/usb_host_vcp;
            zlib;
          namespace: "espressif"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
