name: Vulnerability scan

on:
  schedule:
     - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  vulnerability-scan:
    name: Vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install esp-idf-sbom
        run: pip3 install esp-idf-sbom

      - name: Vulnerability scan
        id: scan
        run: python3 -m esp_idf_sbom manifest check

      - name: Send result
        if: ${{ !cancelled() }}
        env:
          MATTERMOST_WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK }}
          # Uses ternary operator. The double quotes are needed because of the colons
          # for mattermost markup, which are confusing the yaml parser.
          MSG: "${{ steps.scan.outcome == 'success' && ':large_green_circle: No vulnerabilities found' || ':red_circle: New vulnerabilities found' }}"
          JOB_URL: ${{ format('{0}/{1}/actions/runs/{2}', github.server_url, github.repository, github.run_id) }}
          USER_NAME: ${{ 'idf-extra-components' }}
        run: |
          curl --no-progress-meter -i -X POST -H 'Content-Type: application/json'\
               -d "{\"username\": \"${USER_NAME}\", \"text\": \"${MSG} ${JOB_URL}\"}"\
               "$MATTERMOST_WEBHOOK"
